[package]
name = "qr_gen"
version = "2.1.0"
edition = "2021"
authors = ["Sharif <sharifakab@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "^0.25"
qrcode = "^0.14"